add error information for when sonatype fails
Codearte/gradle-nexus-staging-plugin pull request #32
Opened 2016-12-23 17:05 UTC by deanhiller

This adds the info so e.getMessage() when used which is printed when using --stacktrace.  Also, we log the same thing as well for those not using --stacktrace as this is a pretty important failure and one needs to know the issue that occurred from the remote end.

2016-12-23 17:26 UTC, deanhiller commented
The result after using my local install of this plugin is something like this...

Caused by: org.gradle.api.UncheckedIOException: org.apache.http.client.HttpResponseException: 500:Server Error  body=[errors:[[id:*, msg:Unhandled: Staging repository is already transitioning: orgwebpieces-1084]]]
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: org.apache.http.client.HttpResponseException: 500:Server Error  body=[errors:[[id:*, msg:Unhandled: Staging repository is already transitioning: orgwebpieces-1084]]]
        at io.codearte.gradle.nexus.infra.SimplifiedHttpJsonRestClient.post(SimplifiedHttpJsonRestClient.groovy:67)
        at io.codearte.gradle.nexus.logic.RepositoryPromoter.promoteRepositoryWithIdAndStagingProfileId(RepositoryPromoter.groovy:15)
        at io.codearte.gradle.nexus.PromoteRepositoryTask.doAction(PromoteRepositoryTask.groovy:23)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        ... 75 more

2016-12-23 21:27 UTC, szpak reviewed
And thanks for the contribution :).

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +			//TODO: Add better error handling (e.g. display error message received from server, not only 500 + not fail on 404 in 'text/html')
This comment is no longer valid after your changes :).

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +			throw new HttpResponseException(e.getStatusCode(), message)
We lose original stacktrace. Please include `e` as a cause.

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +		} catch(groovyx.net.http.HttpResponseException e) {
Missing space after `catch`

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +			String message = "${resp.statusLine.statusCode}:${resp.statusLine.reasonPhrase}  body=${resp.data}"
`  ` (two spaces) before `body` - one would be enough.

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +		}
Please reformat this code fragment in general. It seems your are using tabs instead of spaces.

2016-12-23 21:27 UTC, szpak commented on src/main/groovy/io/codearte/gradle/nexus/infra/SimplifiedHttpJsonRestClient.groovy
> +		}
I created #33 to better handle that.

2016-12-23 21:28 UTC, szpak requested changes
And thanks for the contribution :).

2016-12-23 23:18 UTC, szpak commented
And you can also squash those commits into one.

2017-01-18 22:19 UTC, szpak commented
@deanhiller Can you fix the things I mentioned in the code review to make this PR being merged?

2017-03-19 21:49 UTC, merged

2017-03-19 21:54 UTC, szpak commented
I reworked it your changes and merged them manually.